Name          = "Wordpress"
Env           = "Dev"
Created_by    = "Mustafa"
Dept          = "IT"
ami           = "ami-0b898040803850657"
instance_type = "t2.micro"
key_name      = "myMacKey"
region        = "us-east-1"
