variable "Name" {}
variable "Env" {}
variable "Created_by" {}
variable "Dept" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "region" {}
variable "appname" {}
variable "min_size" {}
variable "max_size {}
variable "desired_capasity {}
